### ISSUE TITLE
No modules named 'config' found

### ISSUE THREAD

**Issue by kailashlimba1997** [sumanentc/fastapi-celery-rabbitmq-application#1]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\kaila\appdata\local\programs\python\python39\lib\site-packages\billiard\spawn.py", line 165, in spawn_main
    exitcode = _main(fd)
  File "c:\users\kaila\appdata\local\programs\python\python39\lib\site-packages\billiard\spawn.py", line 207, in _main
    self = pickle.load(from_parent)
ModuleNotFoundError: No module named 'config'

**Comment by ggree1** [comment]
OMG, I struggled all day long for this problem.
Finally, the solution was simple.
Celery doesn't support windows properly that's why you and I faced with 'prckle.load... ModuleNotFoundError'.

In windows, prefork pool opiton doesn't work, so install gevent and start up Celery with -P gevent option.
or just start -P solo
